In [2]:
import tensorflow as tf

In [4]:
print(tf.__version__)

2.4.1


In [10]:
scalar = tf.constant(7)
print(scalar)
print(scalar.ndim)

tf.Tensor(7, shape=(), dtype=int32)
0


In [13]:
# playing with vectors 
vector = tf.constant([10, 10])
print(vector)
print(vector.ndim)
print(vector.shape)

tf.Tensor([10 10], shape=(2,), dtype=int32)
1
(2,)


In [20]:
# playing with matrices

matrix = tf.constant([[10, 7], [10, 7]])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[10  7]
 [10  7]], shape=(2, 2), dtype=int32)
2


In [27]:
# create another matrix 
another_matrix = tf.constant([[10., 7.], [1., 2.], [8., 9.]], dtype=tf.float16)
print(another_matrix)
print(another_matrix.ndim)

tf.Tensor(
[[10.  7.]
 [ 1.  2.]
 [ 8.  9.]], shape=(3, 2), dtype=float16)
2


In [30]:
# let's begin creating tensors 
tensor = tf.constant([[1, 2, 3], [1, 2, 3]])
print(tensor)

tf.Tensor(
[[1 2 3]
 [1 2 3]], shape=(2, 3), dtype=int32)


In [32]:
# Creating tensors with tf.VAriable 
changable_tensor = tf.Variable([[10, 7], [7, 10]])
unchangable_tensor = tf.constant([[10, 7], [7, 10]])
print(changable_tensor)
print(unchangable_tensor)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>
tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)


In [41]:
# try to change elements in those different tensors:
changable_tensor[0, 0] = 8
unchangable_tensor[0, 0] = 8

TypeError: 'ResourceVariable' object does not support item assignment

In [42]:
# trying to change the chanagable tensor using another way
changable_tensor[0, 0].assign(8)
print(changable_tensor)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[ 8,  7],
       [ 7, 10]], dtype=int32)>


In [43]:
# trying to change the unchangable tensor using another way
unchangable_tensor[0, 0].assign(8)
print(changable_tensor)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [48]:
# Using random tensors
random_1 = tf.random.Generator.from_seed(42) # setting seed for reproducability
random_1 = random_1.normal(shape=(3, 2))
print(random_1.shape)
print(random_1)

(3, 2)
tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)


In [104]:
# shuffling the order of elements in a tensor tensor
not_shuffled = tf.constant([[-1, 0], [1, 2], [3, 4]])
print(not_shuffled)

shuffled = tf.random.shuffle(not_shuffled, seed=42)

print(shuffled)

tf.Tensor(
[[-1  0]
 [ 1  2]
 [ 3  4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[-1  0]
 [ 1  2]
 [ 3  4]], shape=(3, 2), dtype=int32)


In [114]:

# as you will see bellow after a number of sufflings you will get different results 
shuffled = tf.random.shuffle(not_shuffled, seed=42)

print(shuffled)

tf.Tensor(
[[-1  0]
 [ 3  4]
 [ 1  2]], shape=(3, 2), dtype=int32)


In [128]:
# but this way, you can get the same order! (both the operation-level and global-level seeds need to be set to deterministically produce random output )
tf.random.set_seed(42)
shuffled = tf.random.shuffle(not_shuffled, seed=42)
print(shuffled)

tf.Tensor(
[[-1  0]
 [ 1  2]
 [ 3  4]], shape=(3, 2), dtype=int32)


In [140]:
# Playing with other ways we have to create our tensors
import numpy as np

ones = np.ones(shape=(5, 2, 3))       
print(ones)

ones = np.zeros(shape=(5, 2, 3))       
print(ones)

# turn np ars to tf tensors:

# Hint: you use capital letters for matrix and non-cap for vectors
np_A = np.arange(1, 25, dtype=np.int32) # this will create a tensor-like object!
tf_A = tf.constant(np_A)
tf_B = tf.constant(np_A, shape=(2, 3, 4)) 
print(np_A)
print(tf_A)
print(tf_B)



[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int32)
tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)
