# Just tensor operations!

In [2]:
import tensorflow as tf

In [4]:
print(tf.__version__)

2.4.1


In [10]:
scalar = tf.constant(7)
print(scalar)
print(scalar.ndim)

tf.Tensor(7, shape=(), dtype=int32)
0


In [13]:
# playing with vectors 
vector = tf.constant([10, 10])
print(vector)
print(vector.ndim)
print(vector.shape)

tf.Tensor([10 10], shape=(2,), dtype=int32)
1
(2,)


In [20]:
# playing with matrices

matrix = tf.constant([[10, 7], [10, 7]])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[10  7]
 [10  7]], shape=(2, 2), dtype=int32)
2


In [27]:
# create another matrix 
another_matrix = tf.constant([[10., 7.], [1., 2.], [8., 9.]], dtype=tf.float16)
print(another_matrix)
print(another_matrix.ndim)

tf.Tensor(
[[10.  7.]
 [ 1.  2.]
 [ 8.  9.]], shape=(3, 2), dtype=float16)
2


In [30]:
# let's begin creating tensors 
tensor = tf.constant([[1, 2, 3], [1, 2, 3]])
print(tensor)

tf.Tensor(
[[1 2 3]
 [1 2 3]], shape=(2, 3), dtype=int32)


In [32]:
# Creating tensors with tf.VAriable 
changable_tensor = tf.Variable([[10, 7], [7, 10]])
unchangable_tensor = tf.constant([[10, 7], [7, 10]])
print(changable_tensor)
print(unchangable_tensor)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>
tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)


In [41]:
# try to change elements in those different tensors:
changable_tensor[0, 0] = 8
unchangable_tensor[0, 0] = 8

TypeError: 'ResourceVariable' object does not support item assignment

In [42]:
# trying to change the chanagable tensor using another way
changable_tensor[0, 0].assign(8)
print(changable_tensor)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[ 8,  7],
       [ 7, 10]], dtype=int32)>


In [43]:
# trying to change the unchangable tensor using another way
unchangable_tensor[0, 0].assign(8)
print(changable_tensor)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [48]:
# Using random tensors
random_1 = tf.random.Generator.from_seed(42) # setting seed for reproducability
random_1 = random_1.normal(shape=(3, 2))
print(random_1.shape)
print(random_1)

(3, 2)
tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)


In [104]:
# shuffling the order of elements in a tensor tensor
not_shuffled = tf.constant([[-1, 0], [1, 2], [3, 4]])
print(not_shuffled)

shuffled = tf.random.shuffle(not_shuffled, seed=42)

print(shuffled)

tf.Tensor(
[[-1  0]
 [ 1  2]
 [ 3  4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[-1  0]
 [ 1  2]
 [ 3  4]], shape=(3, 2), dtype=int32)


In [114]:

# as you will see bellow after a number of sufflings you will get different results 
shuffled = tf.random.shuffle(not_shuffled, seed=42)

print(shuffled)

tf.Tensor(
[[-1  0]
 [ 3  4]
 [ 1  2]], shape=(3, 2), dtype=int32)


In [128]:
# but this way, you can get the same order! (both the operation-level and global-level seeds need to be set to deterministically produce random output )
tf.random.set_seed(42)
shuffled = tf.random.shuffle(not_shuffled, seed=42)
print(shuffled)

tf.Tensor(
[[-1  0]
 [ 1  2]
 [ 3  4]], shape=(3, 2), dtype=int32)


In [140]:
# Playing with other ways we have to create our tensors
import numpy as np

ones = np.ones(shape=(5, 2, 3))       
print(ones)

ones = np.zeros(shape=(5, 2, 3))       
print(ones)

# turn np ars to tf tensors:

# Hint: you use capital letters for matrix and non-cap for vectors
np_A = np.arange(1, 25, dtype=np.int32) # this will create a tensor-like object!
tf_A = tf.constant(np_A)
tf_B = tf.constant(np_A, shape=(2, 3, 4)) 
print(np_A)
print(tf_A)
print(tf_B)



[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int32)
tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)


In [141]:
# the most important information about the tensors:
# 1. axis or dimention: a particular axis of the tensor: t[0, :] which is the first row
# 2. size: total num of stuff in the tensor
# 3. rank: # of tensor dimentations => scalar has rank 0, tensor has rank n, matrix has rank 2
# 4. shape

In [151]:
# indexing tensors:
# they can be indexed just like python lists
random_1 = tf.random.Generator.from_seed(42) # setting seed for reproducability
random_1 = random_1.normal(shape=(5, 7, 8, 9))

# here, print the all elements except the first two elements in each dimension except for first and last dimentions that these rules are applied:
# 1. For last dimention we have all of its elements included
# 2. For the first dimention we have just the last element included 
print(random_1[4:, 2:, 2:, :])


tf.Tensor(
[[[[-1.5192095   0.720424    1.0274152   0.8495138  -0.12118822
     1.2286534   1.3224288   0.5263655  -1.0726968 ]
   [-0.15847443 -2.0752518  -2.0175176   1.8219861  -0.17638868
     0.5331409  -0.788109    0.33984604 -1.0300598 ]
   [-1.1844534  -0.7996488  -0.73568696  0.27281994  1.9092387
    -0.6452335  -0.5682918  -2.4179578  -0.949775  ]
   [-0.74240965 -0.17762421 -0.4307022   0.18037981  1.2891542
     0.3617188  -1.2375034   0.981118   -0.5096442 ]
   [-0.1461284   0.3747933   0.22653389 -0.57038045 -0.50904447
     0.4016178   0.10046963 -1.0865864   2.0519838 ]
   [ 0.6308927   0.3077204   0.3900467  -0.11137234 -0.51449716
    -0.46986154 -0.8681604  -0.06980452  0.21168704]]

  [[-1.2618831  -0.6814878  -1.4747126   0.7862976  -0.93069404
    -1.1816639   1.1117176  -1.1115844  -0.23774447]
   [ 1.2730241  -0.81233984 -0.8393727   0.21031417  1.0768498
     0.26008767 -0.35208124 -0.87636274  0.6996424 ]
   [-1.8611109  -0.16546796  0.65970486  0.22830811  0

In [159]:
# get the first element from each dimention from each index except for the final one (the dimention is included by default if you just skip it)
print(random_1[0, 0, 0])

tf.Tensor(
[-0.7565803  -0.06854702  0.07595026 -1.2573844  -0.23193763 -1.8107855
  0.09988727 -0.50998646 -0.7535805 ], shape=(9,), dtype=float32)


In [160]:
# this one should also give the same results with different shape
print(random_1[:1, :1, :1, :])

tf.Tensor(
[[[[-0.7565803  -0.06854702  0.07595026 -1.2573844  -0.23193763
    -1.8107855   0.09988727 -0.50998646 -0.7535805 ]]]], shape=(1, 1, 1, 9), dtype=float32)


In [164]:
# create a rank 2 tensor (2 dimensions), and then upgrade it to a rank 3 tensor (3 dimensions)
rank_2_tensor = tf.constant([[2, 3], [4, 5]])
print(rank_2_tensor.shape)
print(rank_2_tensor.ndim)

(2, 2)
2


In [166]:
# getting the last item of each row:
print(rank_2_tensor[:, -1])

tf.Tensor([3 5], shape=(2,), dtype=int32)


In [167]:
# altering the shape of the tensor (adding extra dimension keeping the exact same information)
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
print(rank_3_tensor.shape)

(2, 2, 1)


In [172]:
# alternative to tf.newaxis

rank_3_tensor_alt = tf.expand_dims(rank_2_tensor, axis=-1) # I used -1 to expand upon the last axis
print(rank_3_tensor_alt.shape)

(2, 2, 1)


In [173]:
print(rank_3_tensor)
print(rank_3_tensor_alt)

tf.Tensor(
[[[2]
  [3]]

 [[4]
  [5]]], shape=(2, 2, 1), dtype=int32)
tf.Tensor(
[[[2]
  [3]]

 [[4]
  [5]]], shape=(2, 2, 1), dtype=int32)


In [176]:
# basic operations with tensors
tensor = tf.constant([[1, 2], [3, 4]])
print(tensor)
print(tensor + 10)
print(tensor / 10)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[11 12]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.1 0.2]
 [0.3 0.4]], shape=(2, 2), dtype=float64)


In [177]:
# it is possible to use the tf.math.multiply which is the tensorflow built-in function,... which by the way is not dot product
print(tf.multiply(tensor, tensor))

tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)


In [182]:
# Matrix multiplication (dot product)
print(tf.matmul(tensor, tensor))


# What if I use @ python operator?
print(tensor @ tensor)


# what about * python operator?
print(tensor * tensor)

tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)
